version: '2.1'

orbs:
  go: circleci/go@1.7.1

executors:
  go:
    docker:
      - image: circleci/golang:1.19

jobs:
  test:
    executor: go
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

  lint:
    executor: go
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Install golangci-lint
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.41.1
      - run:
          name: Run golangci-lint
          command: golangci-lint run -c .golangci.yml


workflows:
  main:
    jobs:
      - test
      - lint:
          filters:
            branches:
              only: main

