import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                hello friend.<br/>
                <br/>
                i'm jon. a software engineer, musician, and climbing enthusiast.<br/>
                currently working at <a href="https://circleci.com">circleci</a>.<br/>
                my passions are the command line and backend development.<br/>
                <br/>
                {/* TODO: add powered by */}
                check out my <Link href="/blog">blog</Link>.<br/>
                you can also read it via the terminal with <code>ssh #FILL ME IN#</code>.<br/>
                <br/>
                check out my <a href="github.com/jclasley">github</a>.
                you can also read it via the terminal with <code>ssh #FILL ME IN#</code>.<br/>
                {/* TODO: add powered by */}
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
          </span>
                </a>
            </footer>
        </div>
    )
}
